member/urls.py
from django.urls import path
# from . import views
from .views import (
    signup,
    login,
    logout,
    profile,
    order,
    rate,
    user_info_update,
    user_info_delete,
    user_info_password,
    service,
    service_cancel,
    service_complete,
    service_cancel_list,
    change_shipping,
    id_find
)

app_name = 'member'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('order/', order, name='order'),
    path('profile-rate/', rate, name='rate'),
    path('profile-update/', user_info_update, name='profile-update'),
    path('profile-delete/', user_info_delete, name='profile-delete'),
    path('profile-password/', user_info_password, name='profile-password'),
    path('service/', service, name='service'),
    path('service-cancel/', service_cancel, name='service-cancel'),
    path('service-cancelList/', service_cancel_list, name='service-cancelList'),
    path('service-complete/', service_complete, name='service-complete'),
    path('change-shipping/', change_shipping, name='change-shipping'),
    path('id-find/', id_find, name='id-find'),
]

nike_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('product.urls')),
    path('member/', include('member.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
]

# 이미지 파일에 대한 path 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('to-checkout/', views.ToCheckout.as_view(), name='to-checkout'),
    # path('complete/', views.CompleteView.as_view(), name='complete'),
    path('complete/<int:order_no>/', views.CompleteView.as_view(), name='complete'),
    path('make-order/', views.MakeOrder.as_view(), name='make-order'),
    path('checkout/', views.checkout, name='checkout'),
    path('shipping/', views.Shippings, name='shipping'),
    path('shipping-show/', views.ShippingShow, name='shipping-show'),
    path('shipping-update/<int:pk>', views.Shipping_update, name='shipping-update'),
    path('shipping-delete/<int:pk>', views.Shipping_delete, name='shipping-delete'),

    # path('product/<int:pk>', views.CategoryDetail.as_view(), name='list'),
    # path('cart/', views.CartList.as_view(), name='cart'),
    # path('product/detail/<int:pk>/', views.ProductDetail.as_view(), name='detail'),
    # path('cart/add/', views.add_cart, name='add-cart'),
    # path('cart/delete-one/', views.cart_delete_one, name='cart-delete-one'),
    # path('cart/delete-all/', views.cart_delete_all, name='cart-delete-all'),
]

product/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.index),
    path('product/about',views.about, name='about'),
    path('product/about/<int:category>/<int:id>',views.aboutDetail.as_view(), name='aboutDetail'),
    path('product/error',views.error,name='error'),
    path('product/all/<int:gender>/<int:id>', views.CategoryDetail.as_view(), name='list'),
    path('product/size/', views.FilterDetail, name='size'),
    path('product/new/<int:pk>', views.NewProductList.as_view(), name='new'),
    path('product/best/<int:pk>', views.BestProductList.as_view(), name='best'),
    path('product/sale/<int:gender>/<int:id>', views.SaleProductList.as_view(), name='sale'),
    path('cart/', views.CartList.as_view(), name='cart'),
    path('product/detail/<int:pk>/', views.ProductDetail.as_view(), name='detail'),
    path('cart/add/', views.add_cart, name='add-cart'),
    path('cart/delete-one/', views.cart_delete_one, name='cart-delete-one'),
    path('cart/delete-all/', views.cart_delete_all, name='cart-delete-all'),
    path('cart/get-option/<int:pk>/', views.get_option, name='get-option'),
    path('cart/change-option/', views.change_option, name='change-option')
]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True, default='라이프스타일')

    def __str__(self):
        return '{} : {}'.format(self.pk, self.name)


class Product(models.Model):
    # 상품번호, 상품명, 상품가격, 카테고리번호, (총재고량), 출시일, 판매량, 썸네일 이미지

    GENDER_CHOICES = (
        ('MEN', 'MEN'),
        ('WOMEN', 'WOMEN'),
    )

    name = models.CharField(max_length=30, unique=False)
    gender = models.CharField(max_length=5, choices=GENDER_CHOICES, default=1)
    price = models.IntegerField()
    style = models.CharField(max_length=10)    # 상품번호. 나중에 blank=false로 바꿀예정
    # 카테고리에 속한 상품 존재하면 카테고리 삭제 불가
    category_id = models.ForeignKey(Category, on_delete=models.PROTECT)
    soldout = models.BooleanField(default=False)   # 재고 있으면 False, 품절이면 True
    release_date = models.DateField()
    sales = models.IntegerField(default=0)   # 판매량 default를 0으로
    thumbnail = models.ImageField(upload_to='product/thumbnail/')

    def __str__(self):
        return '{} : {}'.format(self.pk, self.name)

    def category_name(self):
        return '{} {}'.format(self.gender, self.category_id.name)


class Inventory(models.Model):
    # 상품번호, 사이즈, 재고
    product_id = models.ForeignKey(
        Product, on_delete=models.PROTECT)  # 재고 존재하면 상품 삭제 불가
    size = models.CharField(max_length=10)
    amount = models.IntegerField(default=0)

    def __str__(self):
        return '{}: {}'.format(self.product_id, self.size)

    # def soldout(self):
    #     if (self.amount - self.sale) == 0:
    #         self.soldout = True
    #     else:
    #         self.soldout = False
    #     self.save()


class ProductImage(models.Model):
    product_id = models.ForeignKey(
        Product, on_delete=models.CASCADE)  # 상품 삭제하면 이미지도 함께 삭제
    image = models.ImageField(upload_to='product/detailimage/')

    def __str__(self):
        return '{} image'.format(self.product_id)


class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    inventory_id = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return '{} - {}'.format(self.user_id, self.inventory_id)

product/views.py
from itertools import chain

from django.db.models import Sum, F
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, RedirectView
from .models import Category, Product, ProductImage, Inventory, Cart
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, request, JsonResponse
from django.utils import timezone
import member.urls
import datetime
from django.core import serializers
import json
import itertools

def index(request):
    # 각 카테고리에서 판매량 1순위인 상품 리스트에 추가
    # MEN, WOMEN 구분 함.
    product_list = []
    category = Category.objects.all()
    count = range(1, len(category)+1)
    pro3 = Product.objects.filter(gender__isnull=True)
    for i in count:
        # pro: men의 category_id가 i인 상품 중 판매량 1순위인 상품 1개
        # pro2: women의 category_id가 i인 상품 중 판매량 1순위인 상품 1개
        # pro3: men과 women의 각 카테고리에서 판매량 1순위인 상품 최종 리스트
        pro = Product.objects.filter(gender='MEN', category_id=i).order_by('-sales')[:1]
        pro2 = Product.objects.filter(gender='WOMEN', category_id=i).order_by('-sales')[:1]
        pro3 = itertools.chain(pro, pro2, pro3)
    product_list = pro3
    return render(
        request,
        'product/index.html/',
        {'product_list': product_list},
    )


def about(request):
    return render(
        request,
        'product/about.html/',
        {},
    )

class aboutDetail(ListView):
    model = Product
    template_name = 'product/aboutDetail.html'

    def get_context_data(self, **kwargs):
        context = super(aboutDetail, self).get_context_data(**kwargs)
        category = self.kwargs['category']
        id = self.kwargs['id']

        if category == 1:
            context['category2'] = 'member'
            if id == 0:
                context['category3'] = 'sign-in'
                context['url1'] ='https://github.com/Minsoo-web/django_nike/blob/master/member/views.py#L39'
                context['url2'] ='https://github.com/Minsoo-web/django_nike/blob/master/product/templates/product/base.html#L36'
                context['url3'] ='https://github.com/Minsoo-web/django_nike/blob/master/product/views.py#L391'
            elif id==1:
                context['category3'] = 'sign-up'
                context['url1'] ='https://github.com/Minsoo-web/django_nike/blob/master/member/views.py#L19'
                context['url2'] ='https://github.com/Minsoo-web/django_nike/blob/master/member/static/member/js/member.js#L1'
            else:
                context['category3'] = 'member' 
                context['url1'] ='https://github.com/Minsoo-web/django_nike/blob/master/member/views.py#L162'
                context['url2'] ='https://github.com/Minsoo-web/django_nike/blob/master/member/views.py#L183'
                context['url3'] ='https://github.com/Minsoo-web/django_nike/blob/master/order/views.py#L225'

        elif category == 2:
            context['category2'] = 'order'
            if id == 0:
                context['category3'] = 'grade'
            elif id == 1:
                context['category3'] = 'shipping'
                context['url1'] ='https://github.com/Minsoo-web/django_nike/blob/master/order/static/order/js/checkout-next-step.js#L1'
                context['url2'] ='https://github.com/Minsoo-web/django_nike/blob/master/order/views.py#L198'
                context['url3'] ='https://github.com/Minsoo-web/django_nike/blob/master/order/views.py#L225'
            else : 
                context['category3'] = 'cart'
                context['url1'] ='https://github.com/Minsoo-web/django_nike/blob/master/product/templates/product/detail.html#L121'
                context['url2'] ='https://github.com/Minsoo-web/django_nike/blob/master/product/static/product/js/cart.js#L1'
                context['url3'] ='https://github.com/Minsoo-web/django_nike/blob/master/product/templates/product/cart.html#L60'
        else :
            context['category2'] = 'cancel'
            if id == 0:
                context['category3'] = 'cancelList'
                context['url1'] ='https://github.com/Minsoo-web/django_nike/blob/master/member/static/member/js/service-cancel.js#L9'
                context['url2'] ='https://github.com/Minsoo-web/django_nike/blob/master/member/static/member/js/service-list.js#L1'
            else:
                context['category3'] = 'cancel'

        return context



def error(request):
    return render(
        request,
        'product/error.html/',
        {},
    )


def FilterDetail(request):
    template_name = 'product/product.html'
    if request.method == "POST":
        size_list = request.POST.getlist('size')
        align = request.POST.get('orderType')
        url = request.POST.get('url')
        url = url.split('/')[3:5]

        size_id = []
        for i in size_list:
            product = Inventory.objects.filter(size=i, amount__gt=0).values_list('product_id', flat=True)
            for pro in product:
                size_id.append(pro)

        # 사이즈 필터 선택 유무 flag
        if not size_id:
            size_flag = 0
        else:
            size_flag = 1

        # 정렬 방식 선택 유무 flag
        if align is None:
            align_flag = 0
        else:
            align_flag = 1

        print(size_flag)
        print(align_flag)
        print(size_id)

        if url[0] == '1':
            # MEN 카테고리
            gender = 'Men'
            if url[1] == '0':
                # 신발 전체
                if size_flag == 1:
                    # 사이즈 필터 ON
                    if align_flag == 1:
                        # 정렬 방식 선택(align: 정렬 방식)
                        queryset = Product.objects.filter(gender='MEN', pk__in=size_id)
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json",
                                                             Product.objects.filter(gender='MEN', pk__in=size_id))
                else:
                    # 사이즈 필터 OFF
                    if align_flag == 1:
                        # 정렬 방식 선택(align: 정렬 방식)
                        queryset = Product.objects.filter(gender='MEN')
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json", Product.objects.filter(gender='MEN'))
                category = '신발'
            else:
                # 카테고리 별 신발
                if size_flag == 1:
                    if align_flag == 1:
                        queryset = Product.objects.filter(gender='MEN', category_id=url[1], pk__in=size_id)
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json",
                                                             Product.objects.filter(gender='MEN', category_id=url[1],
                                                                                    pk__in=size_id))
                else:
                    if align_flag == 1:
                        queryset = Product.objects.filter(gender='MEN', category_id=url[1])
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json", Product.objects.filter(gender='MEN', category_id=url[1]))
                category = serializers.serialize("json", Category.objects.filter(pk=url[1]), fields=('name'))
        else:
            # WOMEN 카테고리
            gender = 'Women'
            if url[1] == '0':
                # 신발 전체
                if size_flag == 1:
                    # 사이즈 필터 ON
                    if align_flag == 1:
                        # 정렬 방식 선택(align: 정렬 방식)
                        queryset = Product.objects.filter(gender='WOMEN', pk__in=size_id)
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json",
                                                             Product.objects.filter(gender='WOMEN', pk__in=size_id))
                else:
                    # 사이즈 필터 OFF
                    if align_flag == 1:
                        queryset = Product.objects.filter(gender='WOMEN')
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json", Product.objects.filter(gender='WOMEN'))
                category = '신발'
            else:
                # 카테고리 별 신발
                if size_flag == 1:
                    if align_flag == 1:
                        queryset = Product.objects.filter(gender='WOMEN', category_id=url[1], pk__in=size_id)
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json",
                                                             Product.objects.filter(gender='WOMEN', category_id=url[1],
                                                                                    pk__in=size_id))
                else:
                    if align_flag == 1:
                        queryset = Product.objects.filter(gender='WOMEN', category_id=url[1])
                        product_list = serializers.serialize("json", FilterList(align, queryset))
                    else:
                        product_list = serializers.serialize("json",
                                                             Product.objects.filter(gender='WOMEN', category_id=url[1]))

product/templates/product/aboutDetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Tech View</title>
    <link
      href="{% static 'product/img/favicon 2.ico' %}"
      rel="shortcut icon"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'product/css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'product/css/aboutDetail.css' %}" />
    <!-- jquery cdn -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'product/js/aboutDetail.js' %}"></script>
  </head>
  <body>
    <span id="category2" class="category">{{category2}}</span>
    <span id="category3" class="category">{{category3}}</span>
    {% if category3 == 'sign-up' or category3 == 'cancelList' %}
    <div id="aboutDetail">
      <div class="big">
        <a href="{{url1}}"><div class="codeView">code view</div></a>
      </div>
      <div class="wrapper">
        <a href="{{url2}}"><div class="codeView">code view</div></a>
      </div>
    </div>
    {% else %}
    <div id="aboutDetail">
      <div class="big">
        <a href="{{url1}}"><div class="codeView">code view</div></a>
      </div>
      <div class="wrapper">
        <div class="up">
          <a href="{{url2}}"><div class="codeView">code view</div></a>
        </div>
        <div class="down">
          <a href="{{url3}}"><div class="codeView">code view</div></a>
        </div>
      </div>
    </div>
    {% endif %}
  </body>
</html>

product/templates/product/best.html
{% extends "product/base.html" %} {% load humanize %}

<!-- title 확장 -->
{% block title %} 나이키 {% endblock %}

<!-- content 확장 -->
{% block content %}
<section id="best" class="cover">
  <!-- 왼쪽이 큰 버전 -->
  <!-- lifeStyle -->
  <div class="best-category-gallery">
    <div class="best-category-header">
      <h2 class="main-title">BEST 라이프스타일</h2>
      <!-- 해당 카테고리로 연결하시면 됩니다. -->
      <a href="{% url 'products:list' gender 1 %}">신발 전체 보기</a>
    </div>
    <div class="best-img-box">
      {% for product in life_product_list %}
      <div class="best-img-wrapper">
        <img
          src="{{product.thumbnail.url}}"
          alt="bestLifeStyle{{product.pk}}"
          class="best-img"
        />
        <div class="best-hover-box">
          <h3 class="title">{{product.name}}</h3>
          <h3 class="title">{{product.price|intcomma}}원</h3>
          <a href="/product/detail/{{product.id}}">구매하기</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <!-- 오른쪽이 큰 버전-->
  <!-- 러닝 -->
  <div class="best-category-gallery">
    <div class="best-category-header">
      <h2 class="main-title">BEST 러닝</h2>
      <!-- 해당 카테고리로 연결하시면 됩니다. -->
      <a href="{% url 'products:list' gender 2 %}">신발 전체 보기</a>
    </div>
    <div class="best-img-box-right">
      {% for product in run_product_list %}
      <div class="best-img-wrapper">
        <img
          src="{{product.thumbnail.url}}"
          alt="besk러닝{{product.pk}}"
          class="best-img"
        />
        <div class="best-hover-box">
          <h3 class="title">{{product.name}}</h3>
          <h3 class="title">{{product.price|intcomma}}원</h3>
          <a href="/product/detail/{{product.id}}">구매하기</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <!-- basketball-->
  <div class="best-category-gallery">
    <div class="best-category-header">
      <h2 class="main-title">BEST 농구</h2>
      <!-- 해당 카테고리로 연결하시면 됩니다. -->
      <a href="{% url 'products:list' gender 3 %}">신발 전체 보기</a>
    </div>
    <div class="best-img-box">
      {% for product in bask_product_list %}
      <div class="best-img-wrapper">
        <img
          src="{{product.thumbnail.url}}"
          alt="best농구{{product.pk}}"
          class="best-img"
        />
        <div class="best-hover-box">
          <h3 class="title">{{product.name}}</h3>
          <h3 class="title">{{product.price|intcomma}}원</h3>
          <a href="/product/detail/{{product.id}}">구매하기</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <!-- soccer -->
  <div class="best-category-gallery">
    <div class="best-category-header">
      <h2 class="main-title">BEST 축구</h2>
      <!-- 해당 카테고리로 연결하시면 됩니다. -->
      <a href="{% url 'products:list' gender 4 %}">신발 전체 보기</a>
    </div>
    <div class="best-img-box-right">
      {% for product in soc_product_list %}
      <div class="best-img-wrapper">
        <img
          src="{{product.thumbnail.url}}"
          alt="나이키리액트비전"
          class="best-img"
        />
        <div class="best-hover-box">
          <h3 class="title">{{product.name}}</h3>
          <h3 class="title">{{product.price|intcomma}}원</h3>
          <a href="/product/detail/{{product.id}}">구매하기</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <!-- flip-flops -->
  <div class="best-category-gallery">
    <div class="best-category-header">
      <h2 class="main-title">BEST 샌들&슬리퍼</h2>
      <!-- 해당 카테고리로 연결하시면 됩니다. -->
      <a href="{% url 'products:list' gender 5 %}">신발 전체 보기</a>
    </div>
    <div class="best-img-box flip">
      {% for product in flip_product_list %}
      <div class="best-img-wrapper flip">
        <img src="{{product.thumbnail.url}}" alt="flip-flops{{product.pk}}"  class="best-img"/>
        <div class="best-hover-box">
          <h3 class="title">{{product.name}}</h3>
          <h3 class="title">{{product.price|intcomma}}원</h3>
          <a href="/product/detail/{{product.id}}">구매하기</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

product/templates/product/cart.html
{% extends "product/base.html" %} {% load humanize %}

<!-- title -->
{% block title %} 장바구니-나이키 {% endblock %}

<!-- 템플릿 확장 -->
{% load static %}
<!-- 링크 -->
{% block link %}
<link rel="stylesheet" href="{% static 'product/css/cart.css' %}" />
<script src="{% static 'product/js/cart.js' %}"></script>
{% endblock %}
<!-- option 변경 모달창 -->
{% block modal %}
<div class="cart-option-modal" style="display: none;">
  <p class="close-modal"><i class="xi-close"></i></p>
  <div class="cart-modal-box">
    <div class="cart-gallery">
      <div class="cart-product-img-wrapper" id="thumNail">
        <img src="" alt="썸네일" />
      </div>
    </div>
    <div class="cart-option-box">
      <div class="cart-product-info-header">
        <p>
          <span class="cart-product-category"></span
          ><span class="cart-product-price color-orange"></span>
        </p>
        <h2 class="big-title"></h2>
      </div>
      <div class="order-box">
        <div class="size-wrapper">
          <h3>사이즈 선택</h3>
          <span id="size-alert" class="color-orange"></span>
          <div class="size-selector"></div>
        </div>
        <div class="cart-btn-wrapper">
          <span class="round-btn-big white">옵션변경</span>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<!-- content -->
{% block content %}
<section id="cart" class="cover">
  <div class="cart-header">
    <h1>장바구니</h1>
    <span>{{ total_quantity }}</span><span>개 상품</span>
  </div>
  {% if total_quantity == 0 %}
  <div id="no-items">
    <i class="xi-cart"></i>
    <h2>장바구니에 담긴 상품이 없습니다.</h2>
    <a href="/"><span>계속 쇼핑하기</span></a>
  </div>
  {% else %}
  <div class="cart-list-delete">
    <span onclick="delete_all({{user.id}})">전체삭제</span>
  </div>
  <div class="cart-contents">
    <ul class="cart-list-wrapper">
      {% for c in cart %}
      <li>
        <div class="cart-itemimg-wrapper">
          <img
            src="{{ c.inventory_id.product_id.thumbnail.url }}"
            alt="아이템1"
          />
        </div>
        <div class="cart-item-detail">
          <ul>
            <li>{{ c.inventory_id.product_id.name }}</li>
            <li>스타일 : {{ c.inventory_id.product_id.style }}</li>
            <li>
              사이즈 : <span class="{{c.pk}}">{{ c.inventory_id.size }}</span>
            </li>
            <li>수량 : {{ c.quantity }}</li>
            <li class="cart-mobile cart-item-option">
              <span class="{{ c.inventory_id.product_id.pk }}" value="{{c.pk}}"
                >옵션 변경</span
              >
              <span class="color-orange"
                >{{ c.inventory_id.product_id.price|intcomma }}</span
              >
            </li>
          </ul>
        </div>
        <div class="cart-item-option cart-desktop">
          <span class="{{ c.inventory_id.product_id.pk }}" value="{{c.pk}}"
            >옵션 변경</span
          >
          <span class="color-orange"
            >{{ c.inventory_id.product_id.price|intcomma }}</span
          >
        </div>
        <div class="cart-item-delete">
          <i class="xi-close" onclick="delete_one({{ c.id }})"></i>
        </div>
      </li>
      {% endfor %}
    </ul>

    <div class="cart-order-box">
      <div class="cart-order-header">
        <strong class="title">주문예정금액</strong>
      </div>

      <ul class="cart-order-info">
        <li class="order-info-list">
          <span>상품 금액</span><span>{{amount|intcomma}}원</span>
        </li>
        <li class="order-info-list">
          <span>예상 배송비</span><span>{{shipping_price|intcomma}}원</span>
        </li>
        <li class="order-info-list color-orange">
          <span>상품 할인 금액</span><span>0원</span>
        </li>
        <li class="order-info-list color-orange">
          <span>주문 할인 금액</span><span>0원</span>
        </li>
        <li class="order-info-list color-orange">
          <span>총 결제 예정 금액</span><span>{{total_price|intcomma}}원</span>
        </li>
        <a href="#" onclick="order()">주문하기</a>
      </ul>
    </div>
  </div>
  {% endif %}
</section>

<script>
  function delete_one(id) {
    $.ajax({
      type: "POST",
      url: "{% url 'products:cart-delete-one' %}",
      data: {'cart-id': id, csrfmiddlewaretoken: '{{ csrf_token }}'},
      success: function(response) {
        var answer = response.result;
        if (answer == 'success') {
          alert("삭제되었습니다");
          window.location.href = "{% url 'products:cart' %}";
        }
        else if (answer == 'no user') {
          window.location.href = "{% url 'member:login' %}";
        }
      }
    });
  }

  function delete_all(user_id) {
    $.ajax({
      type: "POST",
      url: "{% url 'products:cart-delete-all' %}",
      data: {'user-id': user_id, csrfmiddlewaretoken: '{{ csrf_token }}'},
      success: function(response) {
        var answer = response.result;
        if (answer == 'success') {
          alert("삭제되었습니다");
          window.location.href = "{% url 'products:cart' %}";
        }
        else if (answer == 'no user') {
          window.location.href = "{% url 'member:login' %}";
        }
      }
    });
  }

  function order() {
    var order_list = [];
    {% for c in cart %}
    order_list.push({ 'inventory-id': {{ c.inventory_id.id }}, quantity: {{ c.quantity }} });
    {% endfor %}4
    var order_list_str = JSON.stringify(order_list);
    var amount = {{ amount }};
    var shipping_price = {{ shipping_price }};
    var total_price = {{ total_price }};
    $.ajax({
      type: "POST",
      url: "{% url 'order:to-checkout' %}",
      data: {'is-cart': 1,
             'order-list': order_list_str,
             'amount': amount,
             'shipping-price': shipping_price,
             'total-price': total_price,
              csrfmiddlewaretoken: '{{ csrf_token }}'},
      dataType:'json',
      success: function(response) {
        var answer = response.result;
        if (answer == 'success') {
          window.location.href = "{% url 'order:checkout' %}";
        }
        else if (answer == 'no user') {
          window.location.href = "{% url 'member:login' %}";
        }
        else {
          var message = response.message;
          var product = response.product;
          if (message == 'out of stock') {
            alert("재고가 부족합니다\n(상품명 : "+product+")")
          }
        }
      }
    });
  }
</script>
{% endblock %}

product/templates/product/error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% block title %}
    <title>Error !</title>
    {% endblock %}
    <link
      href="{% static 'product/img/favicon.ico' %}"
      rel="icon"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'product/css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'product/css/error.css' %}" />
  </head>
  <body>
    <div id="error-box">
      <div class="logo"></div>
      {% block content %}
      <p class="error-title">서비스 이용에 불편을 드려서 죄송합니다.</p>
      <div class="error-content">
        <p>(404-NOT FOUND)</p>
        <p>현재 서비스에 일시적인 오류가 발생했습니다.</p>
        <p>
          이용에 불편을 드린 점 진심으로 사과 드리며, 고객 여러분의 양해 부탁
          드립니다.
        </p>
      </div>
      {% endblock %}
      <footer>
        <span
          >관련문의사항은 저희 GitHub Repository에 관련 Issues를 남겨주시면
          친절히 답변 드리고 수정하겠습니다.
        </span>
        <span
          >GitHub Repository :
          <a href="https://github.com/chohae0319/django_nike"
            >Nike Shoes Clone Page</a
          ></span
        >
        <a href="/"><span class="home">홈페이지</span></a>
      </footer>
    </div>
  </body>
</html>