member/urls.py
from django.urls import path
# from . import views
from .views import (
    signup,
    login,
    logout,
    profile,
    order,
    rate,
    user_info_update,
    user_info_delete,
    user_info_password,
    service,
    service_cancel,
    service_complete,
    service_cancel_list,
    change_shipping,
    id_find
)

app_name = 'member'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('order/', order, name='order'),
    path('profile-rate/', rate, name='rate'),
    path('profile-update/', user_info_update, name='profile-update'),
    path('profile-delete/', user_info_delete, name='profile-delete'),
    path('profile-password/', user_info_password, name='profile-password'),
    path('service/', service, name='service'),
    path('service-cancel/', service_cancel, name='service-cancel'),
    path('service-cancelList/', service_cancel_list, name='service-cancelList'),
    path('service-complete/', service_complete, name='service-complete'),
    path('change-shipping/', change_shipping, name='change-shipping'),
    path('id-find/', id_find, name='id-find'),
]

nike_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('product.urls')),
    path('member/', include('member.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
]

# 이미지 파일에 대한 path 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('to-checkout/', views.ToCheckout.as_view(), name='to-checkout'),
    # path('complete/', views.CompleteView.as_view(), name='complete'),
    path('complete/<int:order_no>/', views.CompleteView.as_view(), name='complete'),
    path('make-order/', views.MakeOrder.as_view(), name='make-order'),
    path('checkout/', views.checkout, name='checkout'),
    path('shipping/', views.Shippings, name='shipping'),
    path('shipping-show/', views.ShippingShow, name='shipping-show'),
    path('shipping-update/<int:pk>', views.Shipping_update, name='shipping-update'),
    path('shipping-delete/<int:pk>', views.Shipping_delete, name='shipping-delete'),

    # path('product/<int:pk>', views.CategoryDetail.as_view(), name='list'),
    # path('cart/', views.CartList.as_view(), name='cart'),
    # path('product/detail/<int:pk>/', views.ProductDetail.as_view(), name='detail'),
    # path('cart/add/', views.add_cart, name='add-cart'),
    # path('cart/delete-one/', views.cart_delete_one, name='cart-delete-one'),
    # path('cart/delete-all/', views.cart_delete_all, name='cart-delete-all'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
from django.utils import timezone


class Order(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(default=timezone.now)
    amount = models.IntegerField(default=0)               # 상품 금액
    shipping_price = models.IntegerField(default=0)       # 배송비
    total_price = models.IntegerField(default=0)          # 총 결제 금액
    # 받는 사람 정보
    receive_address = models.CharField(max_length=70)
    receive_name = models.CharField(max_length=10)
    receive_phone = models.CharField(max_length=11)
    memo = models.CharField(max_length=100, blank=True)     # 배송요청사항

    def __str__(self):
        return '{}. {} - {}'.format(self.pk, self.order_date.strftime("%Y-%m-%d"), self.user_id)


class OrderList(models.Model):  # Order 모델에 대한 상세내역 담는 클래스
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.PROTECT)
    size = models.IntegerField()
    quantity = models.IntegerField()
    status = models.IntegerField(default=0)     # 0: 결제완료, 1: 배송중, 2: 배송완료, 3: 주문취소

    def __str__(self):
        return '{}({}) : {}'.format(self.order_id.pk, self.pk, self.product_id)


class Shipping(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    destination_nickname = models.CharField(max_length=100)
    receiver = models.CharField(max_length=100)
    receiver_phone = models.CharField(max_length=100)
    receiver_address = models.CharField(max_length=100)

order/forms.py
from django import forms
from .models import Shipping

class ShippingForm(forms.ModelForm):

    class Meta:
        model = Shipping
        fields = ['destination_nickname',
                  'receiver', 'receiver_phone', 'receiver_address']

order/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.db.models import Sum
from django.db import transaction
from django.views.generic import TemplateView, View
from product.models import Inventory, Cart
from .models import Order, OrderList, Shipping
from django.http import HttpResponse
import json
import order.exceptions
from .forms import ShippingForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='/member/login/')
def checkout(request):
    # 세션에서 order_info 가져오기
    order_info = request.session['order_info']

    # order_list 만들기
    order_list = []
    for i in json.loads(order_info['order_list']):
        item = {}
        item['inventory'] = Inventory.objects.get(id=i['inventory-id'])
        item['quantity'] = i['quantity']
        order_list.append(item)

    # 배송지 목록을 불러옴
    shipping_instance = Shipping.objects.filter(user_id=request.user)
    #shipping_instance = get_object_or_404(Shipping)
    if request.method == 'POST':
        ship = Shipping.objects.create(user_id=request.user)
        shipping = ShippingForm(request.POST, instance=ship)
        if shipping.is_valid():
            shipping.save()
            return redirect('order:shipping-show')
    else:
        form = ShippingForm()
    return render(request, 'order/checkout.html', {'order_list': order_list, 'shipping_instance': shipping_instance, "form": form})


class ToCheckout(View):
    def post(self, request):
        # 로그인 안되어있으면 no user 반환
        if not request.user.is_authenticated:
            return HttpResponse(json.dumps({'result': 'no user'}), content_type="application/json")

        # 품절 검사
        for i in json.loads(request.POST.get('order-list', False)):
            inventory = Inventory.objects.get(id=i['inventory-id'])
            amount = inventory.amount
            quantity = i['quantity']
            if amount < quantity:
                return HttpResponse(json.dumps(
                    {'result': 'fail', 'message': 'out of stock', 'product': inventory.product_id.name}),
                    content_type="application/json")

        request.session['order_info'] = {}
        request.session['order_info']['is_cart'] = int(
            request.POST.get('is-cart', False))
        request.session['order_info']['order_list'] = request.POST.get(
            'order-list', False)
        request.session['order_info']['amount'] = request.POST.get(
            'amount', False)
        request.session['order_info']['shipping_price'] = request.POST.get(
            'shipping-price', False)
        request.session['order_info']['total_price'] = request.POST.get(
            'total-price', False)
        return HttpResponse(json.dumps({'result': 'success'}), content_type="application/json")


class CompleteView(TemplateView):
    template_name = 'order/complete.html'

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)

        # order를 context에 추가
        order_no = self.kwargs['order_no']
        context['order'] = Order.objects.get(id=order_no)

        # order_list를 context에 추가
        context['order_list'] = OrderList.objects.filter(order_id=order_no)

        return context


class MakeOrder(View):
    def post(self, request):
        # 로그인 안되어있으면 no user 반환
        if not request.user.is_authenticated:
            return HttpResponse(json.dumps({'result': 'no user'}), content_type="application/json")

        # 로그인한 유저 정보 가져오기
        user_id = request.user

        # 세션에서 order_info 가져오기
        order_info = self.request.session.pop('order_info', None)

        # order_list 변환
        order_list = []
        for i in json.loads(order_info['order_list']):
            item = {}
            item['inventory_id'] = Inventory.objects.get(id=i['inventory-id'])
            item['product_id'] = item['inventory_id'].product_id
            item['size'] = item['inventory_id'].size
            item['quantity'] = i['quantity']
            item['is_soldout'] = False
            order_list.append(item)

        # is_cart 정보
        is_cart = order_info['is_cart']

        # 배송 정보
        receive_address = request.POST.get('receive_address', False)
        receive_name = request.POST.get('receive_name', False)
        receive_phone = request.POST.get('receive_phone', False)
        memo = request.POST.get('memo', False)

        # 결제 금액
        amount = order_info['amount']
        shipping_price = order_info['shipping_price']
        total_price = order_info['total_price']

        # 주문 완료 절차
        # 1. 재고 검사
        # 2. 전 사이즈 재고 하나도 없으면 product 모델에서 품절 표시하기
        # 3. product 모델 판매량 늘리기
        # 4. Order, OrderList 모델 insert
        # => 1번 과정에서 재고 부족으로 exception 발생시 다시 처음 상태로 롤백 시켜야 함(transaction.atomic으로 처리)

        try:
            with transaction.atomic():
                # 1. 재고 검사
                for item in order_list:
                    # 재고 없으면 예외 발생
                    if item['inventory_id'].amount < item['quantity']:
                        # out_of_stock_product = item['product_id'].name
                        raise order.exceptions.OutOfStockError()
                    # 재고 줄이기
                    item['inventory_id'].amount -= item['quantity']
                    item['inventory_id'].save()

                # 2~3. 품절 검사 & 판매량 늘리기
                for item in order_list:
                    # 품절 검사
                    all_inventory = Inventory.objects.filter(
                        product_id=item['product_id'])
                    total_amount = all_inventory.aggregate(
                        total_amount=Sum('amount'))['total_amount']

                    # for inventory in all_inventory:
                    #     if inventory.amount <= 0:
                    #         inventory.soldout = True        # Inventory 모델의 soldout을 True로
                    #         inventory.save()

                    if total_amount <= 0:
                        # Product 모델의 soldout을 True로
                        item['product_id'].soldout = True

                    # 판매량 늘리기
                    item['product_id'].sales += item['quantity']
                    item['product_id'].save()

                # 4. Order, OrderList 모델 insert
                order_obj = Order(user_id=user_id,
                                  amount=amount,
                                  shipping_price=shipping_price,
                                  total_price=total_price,
                                  receive_address=receive_address,
                                  receive_name=receive_name,
                                  receive_phone=receive_phone,
                                  memo=memo)
                order_obj.save()
                order_no = order_obj.pk

                for item in order_list:
                    order_list_obj = OrderList(order_id=order_obj,
                                               product_id=item['product_id'],
                                               size=item['size'],
                                               quantity=item['quantity'])
                    order_list_obj.save()

                # 장바구니에서 주문했을 시, 장바구니에 담겨있는 상품들 삭제, 장바구니 개수 세션 삭제
                if is_cart:
                    data = Cart.objects.filter(user_id=user_id)
                    data.delete()
                    request.session.pop('cart_count', None)

                return HttpResponse(json.dumps({'result': 'success', 'order_no': order_no}), content_type="application/json")

        # 재고 부족시
        except order.exceptions.OutOfStockError as e:
            return HttpResponse(json.dumps({'result': 'fail', 'message': 'out of stock'}), content_type="application/json")

        # # 기타 에러상황
        # except Exception as e:
        #     return HttpResponse(json.dumps({'result': 'fail', 'message': 'unknown error'}), content_type="application/json")


def Shippings(request):
    if request.method == 'POST':
        ship = Shipping.objects.create(user_id=request.user)
        shipping = ShippingForm(request.POST, instance=ship)
        if shipping.is_valid():
            shipping.save()
            return redirect('order:shipping-show')
    else:
        form = ShippingForm()
    return render(request, 'order/shipping.html', {'ship': form})


@login_required(login_url='/member/login/')
def ShippingShow(request):
    shipping_instance = Shipping.objects.filter(user_id=request.user)
    #shipping_instance = get_object_or_404(Shipping)
    if request.method == 'POST':
        ship = Shipping.objects.create(user_id=request.user)
        shipping = ShippingForm(request.POST, instance=ship)
        if shipping.is_valid():
            shipping.save()
            return redirect('order:shipping-show')
    else:
        form = ShippingForm()
    return render(request, 'order/shipping-show.html', {'shipping_instance': shipping_instance, "form": form})


@login_required(login_url='/member/login/')
def Shipping_update(request, pk):
    ship = Shipping.objects.get(id=pk)
    pk = ship.pk
    if request.method == 'POST':
        shipping = ShippingForm(request.POST, instance=ship)
        if shipping.is_valid():
            shipping.save()
            return redirect('order:shipping-show')

    else:
        ship = ShippingForm(instance=ship)
    return


@login_required(login_url='/member/login/')
def Shipping_delete(request, pk):
    ship = Shipping.objects.get(id=pk)
    if request.method == 'POST':
        ship.delete()
        return redirect('order:shipping-show')
    return render(request, 'order/shipping-delete.html', {'ship': ship})

order/templates/order/checkout.html
<!-- 확장 -->
{% extends "product/base.html" %}

<!-- 링크확장 -->
{% load static %}
<!-- 링크확장 -->
{% block link %}
<link rel="stylesheet" href="{% static 'product/css/cart.css' %}" />
<link rel="stylesheet" href="{% static 'order/css/checkout.css' %}" />
<script src="{% static 'order/js/checkout-next-step.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}

<!-- 정수 필터 확장-->
{% load humanize %}

<!-- title 확장 -->
{% block title %} 나이키 {% endblock %}

<!-- content -->
{% block content %}
<section id="checkout" class="cover">
  {% if user.is_authenticated %}
  <div class="checkout-header-box">
    <h1 class="main-title">주문결제</h1>
  </div>
  <div class="checkout-main-box">
    <div class="client-detail-box">
      <div class="checkout-tab-box">
        <ul class="checkout-list-box">
          <input
            type="checkbox"
            name="checkout-tab-menu"
            id="checkout-client-detail"
          />
          <label for="checkout-client-detail">
            <li class="checkout-list-header">
              <span>주문 고객</span>
              <i class="xi-plus"><span id="username">{{ user.email }}</span></i>
              <i class="xi-minus"></i>
            </li>
          </label>
          <li>
            <span>{{ user.username }}</span>
          </li>
          <li>
            <span>{{user.email}}</span>
          </li>
        </ul>
      </div>
      <div class="checkout-tab-box" id="checkout-address-box">
        <!-- 배송지가 없을 경우 -->
        {% if not shipping_instance %}
        <ul class="checkout-list-box">
          <input
            type="checkbox"
            checked
            name="checkout-tab-menu"
            id="checkout-address-detail"
          />
          <label for="checkout-address-detail">
            <li class="checkout-list-header">
              <span>배송지 정보</span>
              <i class="xi-plus"><span id="after-address"></span></i>
              <i class="xi-minus"></i>
            </li>
          </label>
          <li id="address-list1">
            <div>
              <span>받으시는 분</span>
              <span id="receive_name_info" class="alert-msg"></span>
              <input type="text" name="name" autofocus placeholder="이름" id="receive_name" class="input-info"/>
            </div>
            <div>
              <span>연락처</span>

              <span id="receive_phone_info" class="alert-msg"></span>
                <input
                  name="phone"
                  type="text"
                  placeholder="-없이 입력"
                  id="receive_phone"
                  class="input-info"
                />
            </div>
          </li>
          <li>
            <span>배송 주소</span>
            <span id="receive_address_info" class="alert-msg"></span>
            <input
            name="address"
              type="text"
              placeholder="나머지 주소 입력"
              id="receive_address"
              class="input-info"
            />

          </li>
          <li>
            <span>배송 메모를 입력해주세요</span>
            <span id="receive_memo_info" class="alert-msg"></span>
            <input
            name="memo"
              type="text"
              placeholder="ex. 부재시 문 앞에 놔주세요"
              id="memo"
              class="input-info"
            />
          </li>
          <li>
            <p id="alert-msg-next"></p>
            <a href="/cart"><span>장바구니 바로가기</span></a>
            <button id="checkout-next">다음단계 진행</button>
            <button id="modify-client-detail" style="display: none;">수정하기</button>
            <button id="modify-client" style="display: none;">수정완료</button>
          </li>
        </ul>
        <!-- 배송지가 있다면 -->
    {% else %}
    <ul class="checkout-list-box" id="checkout-address-wrapper">
      <input
        type="checkbox"
        checked
        name="checkout-tab-menu"
        id="checkout-address-detail"
      />
      <label for="checkout-address-detail">
        <li class="checkout-list-header">
          <span>배송지 정보</span>
          <i class="xi-plus"><span id="after-address"></span></i>
          <i class="xi-minus"></i>
        </li>
      </label>
      <li id="input-user_address">
        <input type="radio" name="address-tab" checked value="oldAddress" id="checkout-address-tab-old">
        <input type="radio" name="address-tab" value="newAddress" id="checkout-address-tab-new">
        <div class="tab-header">
          <label id="checkout-address-label-old" for="checkout-address-tab-old">이전 주소</label>
          <label id="checkout-address-label-new" for="checkout-address-tab-new">새로 입력</label>
        </div>
        {% for ship in shipping_instance %}
        <div class="checkout-address-oldList">
          <span class="receiver-name">{{ ship.receiver }}</span>
          <span class="receiver-address">{{ ship.receiver_address }}</span>
          <span class="receiver-phone">{{ ship.receiver_phone }}</span>
        </div>
        {% endfor %}
        <div class="checkout-address-memo">
          <input type="text" placeholder="배송 메모를 입력해주세요" id="checkout-address-memo">
        </div>

        <!-- 새 배송지 입력 -->
        <div class="checkout-address-newList">
          <ul>
            <li>
              <span>받으시는 분</span>
              <span id="receive_name_info" class="alert-msg"></span>
              <input type="text" name="name" autofocus placeholder="이름" id="receive_name" class="input-info"/>
            </li>
            <li>
              <span>연락처</span>
              <span id="receive_phone_info" class="alert-msg"></span>
                <input
                  name="phone"
                  type="text"
                  placeholder="-없이 입력"
                  id="receive_phone"
                  class="input-info"
                />
            </li>
            <li>
              <span>배송 주소</span>
              <span id="receive_address_info" class="alert-msg"></span>
              <input
              name="address"
                type="text"
                placeholder="나머지 주소 입력"
                id="receive_address"
                class="input-info"
              />

            </li>
            <li>
              <span>배송 메모를 입력해주세요</span>
              <span id="receive_memo_info" class="alert-msg"></span>
              <input
              name="memo"
                type="text"
                placeholder="ex. 부재시 문 앞에 놔주세요"
                id="memo"
                class="input-info"
              />
            </li>
          </ul>
        </div>
      </li>
      <li id="before-next-step" style="display: none;">
        <p>
          <span>받으시는 분 :</span>
          <span class="after-checkout" id="checkout-username"></span>
        </p>
        <p>
          <span>받으실 주소 :</span>
          <span class="after-checkout" id="checkout-address"></span>
        </p>
        <p>
          <span>연락받으실 번호 :</span>
          <span class="after-checkout" id="checkout-phone"></span>
        </p>
        <p>
          <span>부탁하신 배송 메모 :</span>
          <span class="after-checkout" id="checkout-memo"></span>
        </p>
      </li>
      <li>
        <p id="alert-msg-next"></p>
        <a href="/cart"><span>장바구니 바로가기</span></a>
        <button id="checkout-next2">다음단계 진행</button>
      </li>
    </ul>
    {% endif %}
      </div>
      <div class="checkout-tab-box checkout-next-step">
        <ul class="checkout-list-box">
          <input
            type="checkbox"
            name="checkout-tab-menu"
            id="checkout-sale-detail"
          />
          <label for="checkout-sale-detail">
            <li class="checkout-list-header">
              <span>할인/혜택사용</span>
              <i class="xi-plus"></i>
              <i class="xi-minus"></i>
            </li>
          </label>
          <li>
            <span
              >사용 가능한 프로모 코드를 확인하시고 아래 프로코드 란에 입력하여
              사용하세요.</span
            >
          </li>
          <li>
            <!-- 사용가능한 쿠폰이 있을 경우 -->
            <ul>
              <li>
                <!-- 안내 -->
                <span>* 사용 가능한 신규가입 쿠폰이 있습니다.</span>
              </li>
              <li>
                <!-- 코드 -->
                <span>- 쿠폰 코드 : </span>
              </li>
              <li>
                <!-- 주의사항 -->
                <span
                  >- 1만원 할인 적용되며 장바구니 전체에 5만원 이상 구매 시
                  적용됩니다.</span
                >
              </li>
            </ul>
          </li>
          <li>
            <span>프로모 코드</span
            ><input type="text" placeholder="프로모 코드 입력" />
          </li>
        </ul>
      </div>
      <!-- 결제 여부 -->
      <div class="checkout-tab-box checkout-next-step">
        <ul class="checkout-list-box">
          <input
            type="checkbox"
            name="checkout-tab-menu"
            id="checkout-pay-detail"
          />
          <label for="checkout-pay-detail">
            <li class="checkout-list-header">
              <span>결제</span>
              <i class="xi-plus"></i>
              <i class="xi-minus"></i>
            </li>
          </label>
          <li>
            <!-- 이 버튼에 ajax 추가하시면 됩니다. -->
            <!-- 배송지 data : userInfo -->
            <button onclick="makeOrder()">결제하기</button>
            <script>
              function makeOrder() {
                var receive_name = userInfo.name;
                var receive_phone = userInfo.phone;
                var receive_address = userInfo.address;
                var memo = userInfo.memo;
                $.ajax({
                  type: "POST",
                  url: "{% url 'order:make-order' %}",
                  data: {receive_name: receive_name,
                          receive_phone: receive_phone,
                          receive_address: receive_address,
                          memo: memo,
                          csrfmiddlewaretoken: '{{ csrf_token }}'},
                  success: function(response) {
                    var answer = response.result;
                    if (answer == 'success') {
                      var order_no = response.order_no;
                      window.location.href = "/order/complete/" + order_no + "/";
                    }
                    else if (answer == 'no user') {
                      window.location.href = "{% url 'member:login' %}";
                    }
                    else if (answer == 'fail') {
                      if (message == 'out of stock') {
                        alert('품절된 상품입니다.');
                      }
                      else if (message == 'unknown error') {
                        alert('결제 에러가 발생했습니다');
                      }
                    }
                  }
                });
              }
            </script>
          </li>
        </ul>
      </div>
    </div>
    <!-- 주문 상세 정보 -->
    <div class="order-detail-box">
      <div class="cart-order-box">
        <div class="cart-order-header">
          <strong class="title">주문내역</strong>
        </div>
        {% for item in order_list %}
        <div class="order-detail-thumbnail">
          <div class="img-wrapper">
            <img
              src="{{ item.inventory.product_id.thumbnail.url }}"
              alt="주문상품썸네일"
            />
          </div>
          <ul class="cart-order-info">
            <li class="order-info-list"><span>{{ item.inventory.product_id.name }}</span></li>
            <li class="order-info-list"><span>스타일 : {{ item.inventory.product_id.style }}</span></li>
            <li class="order-info-list"><span>사이즈 : {{ item.inventory.size }}</span></li>
            <li class="order-info-list"><span>수량 : {{ item.quantity }}개</span></li>
            <li class="order-info-list color-orange"><span>{{ item.inventory.product_id.price|intcomma }} 원</span></li>
          </ul>
        </div>
        {% endfor %}
        <ul class="cart-order-info">
          <li class="order-info-list">
            <span>상품 금액</span><span>{{ request.session.order_info.amount|intcomma }}원</span>
          </li>
          <li class="order-info-list">
            <span>예상 배송비</span><span>{{ request.session.order_info.shipping_price|intcomma }}원</span>
          </li>
          <li class="order-info-list">
            <span>상품 할인 금액</span><span class="color-orange">0원</span>
          </li>
          <li class="order-info-list">
            <span>주문 할인 금액</span><span class="color-orange">0원</span>
          </li>
          <li class="order-info-list">
            <span>총 결제 예정 금액</span><span class="color-orange">{{ request.session.order_info.total_price|intcomma }}원</span class="cart-item-price">
          </li>
        </ul>
      </div>
    </div>
  </div>
{% else %}
<div class="already-login">
  <h2 class="title">나이키</h2>
  <span>로그인이 필요한 기능입니다.</span>
  <div class="flex-box">
    <a href="/member/login">로그인</a>
    <a href="/">홈으로</a>
  </div>
</div>
{% endif %}
</section>

{% endblock %}

order/templates/order/complete.html
{% extends "product/base.html" %} {% load humanize %}

<!-- 링크확장 -->
{% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'order/css/complete.css' %}" />
{% endblock%}

<!-- block title -->
{% block title %} 나이키 - 주문완료{% endblock %}

<!-- block content -->
{% block content %}
<section class="cover">
  <div class="complete-box">
    <div class="complete-header">
      <h2 class="big-title">주문해 주셔서 감사합니다.</h2>
      <h4>
        배송이 시작되면 SMS/이메일로 배송이 안내 됩니다.
      </h4>
      <a href="/member/order" class="btn-rectangle">주문내역/배송현황</a>
    </div>
    <div class="order-info-box">
      <ul class="order-info-wrapper">
        <li>
          <span class="list-title">주문날짜</span>
          <span>{{ order.order_date|date:'Y-m-d' }}</span>
        </li>
        <li>
          <span class="list-title">결제완료금액</span>
          <span class="color-orange">{{ order.total_price|intcomma }}원</span>
        </li>
      </ul>
      <span>배송주문상품 정보</span>

      <ul class="order-detail-info">
        {% for item in order_list %}
        <li>
          <div class="order-detail-content orderNumber">
            <span class="list-title">주문번호</span>
            <span class="order-number">{{ item.id }}</span>
          </div>

          <div class="order-detail-content orderInfo">
            <span class="list-title">주문상품내역</span>
            <div>
              <div class="complete-img-wrapper">
                <img src="{{ item.product_id.thumbnail.url }}" alt="" />
              </div>
              <p class="complete-oderInfo-detail">
                <span>{{ item.product_id.name }}</span>
                <span>옵션 : {{ item.size }} </span>
                <span>수량 : {{ item.quantity }}개</span>
              </p>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</section>
{%endblock%}

order/templates/order/shipping-delete.html
<form method="POST"
      action="{% url 'order:shipping-delete' pk=ship.pk %}">
    {% csrf_token %}
    <h1>{{ship.destination_nickname}} - 삭제하기</h1>
    <p>정말로 삭제하시겠습니까?</p>
    <input type="submit" value="삭제하기" />
</form>

order/templates/order/shipping-update.html
<form method="POST"
      action="{% url 'order:shipping-update' pk=number %}">
    {% csrf_token %}
    {{ ship }}
    <input type="submit" value="수정하기" />
</form>

order/templates/order/shipping.html
{% extends "member/profile-base.html" %}

{% block profileContent %}

{% if user.is_authenticated %}
<form method="POST" action="{% url 'order:shipping' %}">
    {% csrf_token %}
    {{ ship }}
    <input type="submit" value="배송지 추가" />
</form>
<a href="{% url 'order:shipping-show' %}"><button>배송지목록</button></a>
{% else %}
<div>
    <a href="{% url 'member:login'%}">
    <button type="submit">로그인하기</button>
    </a>
</div>
{% endif %}
{% endblock %}