member/urls.py
from django.urls import path
# from . import views
from .views import (
    signup,
    login,
    logout,
    profile,
    order,
    rate,
    user_info_update,
    user_info_delete,
    user_info_password,
    service,
    service_cancel,
    service_complete,
    service_cancel_list,
    change_shipping,
    id_find
)

app_name = 'member'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('order/', order, name='order'),
    path('profile-rate/', rate, name='rate'),
    path('profile-update/', user_info_update, name='profile-update'),
    path('profile-delete/', user_info_delete, name='profile-delete'),
    path('profile-password/', user_info_password, name='profile-password'),
    path('service/', service, name='service'),
    path('service-cancel/', service_cancel, name='service-cancel'),
    path('service-cancelList/', service_cancel_list, name='service-cancelList'),
    path('service-complete/', service_complete, name='service-complete'),
    path('change-shipping/', change_shipping, name='change-shipping'),
    path('id-find/', id_find, name='id-find'),
]

nike_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('product.urls')),
    path('member/', include('member.urls')),
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
]

# 이미지 파일에 대한 path 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path('to-checkout/', views.ToCheckout.as_view(), name='to-checkout'),
    # path('complete/', views.CompleteView.as_view(), name='complete'),
    path('complete/<int:order_no>/', views.CompleteView.as_view(), name='complete'),
    path('make-order/', views.MakeOrder.as_view(), name='make-order'),
    path('checkout/', views.checkout, name='checkout'),
    path('shipping/', views.Shippings, name='shipping'),
    path('shipping-show/', views.ShippingShow, name='shipping-show'),
    path('shipping-update/<int:pk>', views.Shipping_update, name='shipping-update'),
    path('shipping-delete/<int:pk>', views.Shipping_delete, name='shipping-delete'),

    # path('product/<int:pk>', views.CategoryDetail.as_view(), name='list'),
    # path('cart/', views.CartList.as_view(), name='cart'),
    # path('product/detail/<int:pk>/', views.ProductDetail.as_view(), name='detail'),
    # path('cart/add/', views.add_cart, name='add-cart'),
    # path('cart/delete-one/', views.cart_delete_one, name='cart-delete-one'),
    # path('cart/delete-all/', views.cart_delete_all, name='cart-delete-all'),
]

member/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product


class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cellphone_number = models.FloatField(default=None)
    shipping = models.CharField(max_length=100, default=None)
    account_number = models.IntegerField(default=None)
    user_grade = models.CharField(max_length=100, default=None) # normal, platinum, mvp (3등급)
    coupon = models.CharField(max_length=100, default=None)

    def __str__(self):
        return self.user.username

class OrderItem(models.Model): # 내가 주문한 아이템
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name

class Order(models.Model): # 카트에 들어 있는 아이템
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{} - {}'.format(self.owner, self.ref_code)

member/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email',  'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

    # username필드의 검증에 username이 이미 사용중인지 여부 검사
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('아이디가 이미 사용중입니다')
        return username

    # password1와 password2의 값이 일치하는지 유효성 검사
    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise forms.ValidationError('비밀번호와 비밀번호 확인란의 값이 일치하지 않습니다')
        return password2

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']

member/views.py
import json

from django.db.models import F
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserCreateForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User
from .models import Profile
from product.models import Cart
from django.contrib.auth.decorators import login_required
from order.models import OrderList, Order
from product.models import Cart
from django.http import HttpResponse
import json


def signup(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            email = request.POST['email']
            password = request.POST['password1']
            password2 = request.POST['password2']
            if password != password2:
                return render(request, 'member/signup.html', {'message': 'password not match'})
            else:
                new_user = User.objects.create_user(username, email, password)
                new_user.save()
                return redirect('/')
        except:
            return render(request, 'member/signup.html', {'message': 'member already existed'})
    else:
        form = UserCreateForm()
    return render(request, 'member/signup.html', {'form': form})


def login(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            request.session['cart_count'] = Cart.objects.filter(
                user_id=request.user.pk).count()
        else:
            return render(request, 'member/login.html', {'message': '아이디와 비밀번호가 일치하지 않습니다.', 'login_form': login_form})
        return redirect('/')
    else:
        login_form = AuthenticationForm()

    return render(request, 'member/login.html', {'login_form': login_form})


def logout(request):
    auth_logout(request)
    return redirect('/')


@login_required(login_url='/member/login/')
def rate(request):
    my_profile = Profile.objects.all()
    orders = Order.objects.filter(user_id=request.user)
    total = sum([order.total_price for order in orders])
    if total > 1000000:
        my_profile.user_grade = 'mvp'
        my_profile.coupon = '30%'
    elif total > 500000:
        my_profile.user_grade = 'platinum'
        my_profile.coupon = '20%'
    else:
        my_profile.user_grade = 'normal'
        my_profile.coupon = '10%'
    context = {
        'total': total,
        'my_profile': my_profile
    }
    return render(request, 'member/profile-rate.html', context)


def service(request):
    return render(
        request,
        'member/service.html/',
        {},
    )


@login_required(login_url='/member/login/')
def service_cancel_list(request):
    return render(
        request,
        'member/service-cancelList.html/',
        {},
    )


@login_required(login_url='/member/login/')
def service_complete(request):
    return render(
        request,
        'member/service-complete.html/',
        {},
    )


@login_required(login_url='/member/login/')
def service_cancel(request):
    my_orders = OrderList.objects.all().order_by('-id')
    context = {
        'my_orders': my_orders
    }
    return render(request, 'member/service-cancel.html/', context)


@login_required(login_url='/member/login/')
def profile(request):
    user_id = request.user

    # user_id에 해당하는 order_id 찾아서 리스트로 만들기
    order_id_list = Order.objects.filter(
        user_id=user_id).values_list('id', flat=True)
    my_orders = OrderList.objects.filter(
        order_id__in=order_id_list).order_by('-id')[:4]
    my_carts = Cart.objects.filter(user_id=user_id).order_by('-id')
    my_profile = Profile.objects.all()
    orders = Order.objects.filter(user_id=user_id)
    total = sum([order.total_price for order in orders])
    if total > 150000:
        my_profile.user_grade = 'mvp'
        my_profile.coupon = '30%'
    elif total > 100000:
        my_profile.user_grade = 'platinum'
        my_profile.coupon = '20%'
    else:
        my_profile.user_grade = 'normal'
        my_profile.coupon = '10%'

    context = {
        'my_orders': my_orders,
        'my_carts': my_carts
    }
    return render(request, 'member/profile.html', context)


@login_required(login_url='/member/login/')
def order(request):
    user_id = request.user

    # user_id에 해당하는 order_id 찾아서 리스트로 만들기
    order_id_list = Order.objects.filter(
        user_id=user_id).values_list('id', flat=True)

    my_orders = OrderList.objects.filter(
        order_id__in=order_id_list).order_by('-id')
    context = {
        'my_orders': my_orders
    }
    return render(request, 'member/profile-orders.html', context)


@login_required(login_url='/member/login/')
def user_info_update(request):
    if request.method == 'POST':
        user_change_form = CustomUserChangeForm(
            request.POST, instance=request.user)
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect('member:profile')
    else:
        user_change_form = UserChangeForm(instance=request.user)
    return render(request, 'member/profile-update.html', {'user_change_form': user_change_form})


@login_required(login_url='/member/login/')
def user_info_delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('/')
    return render(request, 'member/profile-delete.html')


@login_required(login_url='/member/login/')
def user_info_password(request):
    if request.method == 'POST':
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            password_change_form.save()
            return redirect('/')
    else:
        password_change_form = PasswordChangeForm(request.user)
    return render(request, 'member/profile-password.html', {'password_change_form': password_change_form})


def change_shipping(request):
    id = int(request.POST['id'])
    receiver = request.POST['receiver']
    phone = request.POST['phone']
    address = request.POST['address']
    memo = request.POST['memo']

    order = OrderList.objects.get(id=id).order_id
    order.receive_name = receiver
    order.receive_phone = phone
    order.receive_address = address
    order.memo = memo
    order.save()

    return HttpResponse(json.dumps({'result': 'success'}), content_type="application/json")


def id_find(request):
    email = request.POST['email']
    # template에서 받아온 email과 일치하는 이메일을 갖는 user queryset 반환
    data = User.objects.filter(email=email)

    datas = []

    for dt in data:
        datas.append({'id': dt.username, 'email': dt.email,
                      'date': dt.date_joined, 'name': dt.last_name + dt.first_name})

    # info = {'username':username, 'name':name, 'user_email':user_email, 'date_joined':date_joined }
    return HttpResponse(json.dumps({'info': datas}, indent=4, sort_keys=True, default=str), content_type="application/json")

member/templates/member/id-find.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>아이디 찾기</title>
    <!-- 링크확장 -->
    {% load static %}
    <script src="{% static 'member/js/id-find.js' %}"></script>
  </head>
  <body>
    <h1>아이디 찾기</h1>
    <form>
      이메일: <input type="text" name="email" id="email" />
      <button id="findid">검색</button>
    </form>
    <br /><br />
    <div id="user-id"></div>
  </body>
</html>

member/templates/member/login.html
{% extends "product/base.html" %}

<!-- title -->
{% block title %}나이키{% endblock %}

<!-- sign-in content -->
{% block content %}
<section class="cover" id="sign-in">
  <div class="sign-in-header">
    <div class="logo-wrapper">
      <img
        src="https://t1.daumcdn.net/cfile/tistory/2425A9455747DAB308"
        alt="나이키로고"
      />
    </div>
    <h1>나이키 로그인</h1>
  </div>

  {% if message %}
  <form method="POST" class="form-box-signIn">
    {% csrf_token %} {{ login_form.as_p }}
    <p class="login-alert-msg">{{ message }}</p>
    <input type="submit" value="로그인" />
    <div class="sign-in-footer">
      <span>회원이 아니신가요? <a href="/member/signup">회원가입하기</a></span>
    </div>
  </form>
  {% else %}
  <form method="POST" class="form-box-signIn">
    {% csrf_token %} {{ login_form.as_p }}
    <input type="submit" value="로그인" />
    <div class="sign-in-footer">
      <span>회원이 아니신가요? <a href="/member/signup">회원가입하기</a></span>
    </div>
  </form>
  {% endif %}

  <!-- js -->
  {% load static %}
  <script src="{% static 'member/js/member.js' %}"></script>
</section>
{% endblock %}

member/templates/member/profile-base.html
<!-- 템플릿 확장 -->
{% extends "product/base.html" %}

<!-- 링크 -->
{% block link %} {% endblock %}

<!-- title -->
{% block title %}마이페이지 - 나이키{% endblock %}

<!-- 좌측 aside -->
{% block aside %}
<aside id="profile">
  <ul id="profile-ul">
    <a href="/member/profile"
      ><li><strong class="big-title">MY PAGE</strong></li></a
    >
    <li><strong>{{ user.username }}</strong></li>
    <li>
      <a href="/member/profile-rate"><strong>회원등급 현황</strong></a>
    </li>
    <li>
      <div>
        <strong>쇼핑정보</strong>
        <a href="/member/order/"><span>주문 배송</span></a>
        <a href="/member/service/"><span>취소 / 반품</span></a>
      </div>
    </li>
    <li>
      <div>
        <strong>활동정보</strong>
        <a href="../../cart"><span>장바구니</span></a>
        <a href=""><span>상품리뷰</span></a>
      </div>
    </li>
    <li>
      <div>
        <strong>나의정보</strong>
        <a href="/order/shipping-show"><span>배송지 관리</span></a>
        <a href="/member/profile-update"><span>회원정보 관리</span></a>
        <a href="/member/profile-password"><span>비밀번호 변경</span></a>
        <a href="/member/profile-delete"><span>회원탈퇴</span></a>
      </div>
    </li>
    <li>
      <div>
        <span>나이키닷컴</span>
        <span>고객센터</span>
        <span>080-022-0182</span>
        <span>9 A.M ~ 8 P.M</span>
      </div>
    </li>
  </ul>
</aside>
{% endblock %}

<!-- content -->
{% block content %}
<section id="profile">
  {% block profileContent %}
  <!-- 카테고리별 콘텐츠 -->
  {% endblock %}
</section>
{% endblock %}

member/templates/member/profile-delete.html
{% extends "member/profile-base.html" %}

<!-- 타이틀 -->
{% block title %}나이키{% endblock %}

<!-- 템플릿 확장 -->
{% load static %}
<!-- 링크 -->
{% block link %}
<link rel="stylesheet" href="{% static 'member/css/profile.css' %}" />
{% endblock %}

<!-- content -->
{% block profileContent %}

<form
  method="POST"
  action="{% url 'member:profile-delete' %}"
  id="profile-delete"
>
  {% csrf_token %}
  <h1 class="profile-update-title">회원탈퇴</h1>
  <p>정말로 탈퇴하시겠습니까?</p>
  <input type="submit" value="탈퇴하기" />
</form>
{% endblock %}

member/templates/member/profile-orders.html
{% extends "member/profile-base.html" %}{% load humanize %}{% load filters %}

<!-- 템플릿 확장 -->
{% load static %}
<!-- 링크 -->
{% block link %}
<link rel="stylesheet" href="{% static 'member/css/profile.css' %}" />
<link rel="stylesheet" href="{% static 'member/css/profile-order.css' %}" />
<link rel="stylesheet" href="{% static 'order/css/shipping.css' %}" />
<script src="{% static 'member/js/change-shipping.js' %}"></script>
{% endblock %}

<!-- modal -->
{% block modal %}
<div id="order-shipping-modal"></div>
<div class="order-shipping-box">
  <label for="order-shipping-modify"><i class="xi-close"></i></label>
  <form class="form-shipping-plus">
    {% csrf_token %}
    <span>받으시는 분</span>
    <input type="text" name="receiver" id="modify-shipping-receiver" />
    <span>주소</span>
    <input type="text" name="receiver_address" id="modify-shipping-address" />
    <span>연락처</span>
    <input type="text" name="receiver_phone" id="modify-shipping-phone" />
    <span>배송 메모</span>
    <input type="text" name="receiver_memo" id="modify-shipping-memo" />
    <input type="hidden" id="modify-shipping-id" />
    <input type="submit" id="modify-button" value="수정하기" />
    <script>
      $("#modify-button").click(function (e) {
        e.preventDefault();

        var id = $("#modify-shipping-id").val();
        var receiver = $("#modify-shipping-receiver").val();
        var phone = $("#modify-shipping-phone").val();
        var address = $("#modify-shipping-address").val();
        var memo = $("#modify-shipping-memo").val();

        $.ajax({
          type: "POST",
          url: "{% url 'member:change-shipping' %}",
          data: {
            id: id,
            receiver: receiver,
            phone: phone,
            address: address,
            memo: memo,
            csrfmiddlewaretoken: "{{ csrf_token }}",
          },
          dataType: "json",
          success: function (response) {
            var answer = response.result;
            if (answer == "success") {
              window.location.href = "{% url 'member:order' %}";
            }
          },
        });
      });
    </script>
  </form>
</div>
{% endblock %}

<!-- content -->
{% block profileContent %}

<div class="profile-list-title">
  <h2 class="big-title">주문내역/배송현황</h2>
</div>
{% if not my_orders %}
<div class="profile-list-view no-itmes">
  <span>최근 등록된 주문내역이 없습니다.</span>
</div>
{% else %}
<div class="order-detail-box">
  {% for order in my_orders %}
  <div class="order-card">
    <!-- 헤더 -->
    <div class="order-detail-info-header">
      <span>주문일 : {{order.order_id.order_date}}</span
      ><span>주문번호 : {{order.pk}}</span>
    </div>
    <!-- 배송지 -->
    <div class="shipping-info-box">
      <div class="shipping-info-wrapper">
        <div class="shipping-info detail-col">
          <p>
            <strong class="title">배송지정보</strong>
            {% if order.status == 0 %}
            <label
              class="change-shipping{{order.pk}}"
              for="order-shipping-modify"
              ><span class="btn-rectangle">배송지 변경</span>
            </label>
            {% endif %}
          </p>
          <!-- <ul class="shipping-point-wrapper">
            <li>
              받으실 주소 :
              <span class="change-shipping{{order.pk}}"
                >{{ order.order_id.receive_address }}</span
              >
            </li>
            <li>
              받으시는 분 :
              <span class="change-shipping{{order.pk}}"
                >{{ order.order_id.receive_name }}</span
              >
            </li>
            <li>
              연락처 :
              <span class="change-shipping{{order.pk}}"
                >{{ order.order_id.receive_phone }}</span
              >
            </li>
            <li>
              메모 :
              <span class="change-shipping{{order.pk}}"
                >{{ order.order_id.memo }}</span
              >
            </li>
          </ul> -->
        </div>
        <div class="order-price detail-col">
          <p><strong class="title">결제금액</strong></p>
          <p>{{ order.order_id.total_price|intcomma }}원</p>
        </div>
      </div>
      <ul class="shipping-point-wrapper">
        <li>
          받으실 주소 :
          <span class="change-shipping{{order.pk}}"
            >{{ order.order_id.receive_address }}</span
          >
        </li>
        <li>
          받으시는 분 :
          <span class="change-shipping{{order.pk}}"
            >{{ order.order_id.receive_name }}</span
          >
        </li>
        <li>
          연락처 :
          <span class="change-shipping{{order.pk}}"
            >{{ order.order_id.receive_phone }}</span
          >
        </li>
        <li>
          메모 :
          <span class="change-shipping{{order.pk}}"
            >{{ order.order_id.memo }}</span
          >
        </li>
      </ul>
      <div class="buy-where">
        <p><strong>구매하신 곳</strong></p>
        <p>NIKE-CLONE.COM</p>
      </div>
    </div>
    <!-- 결제 정보 -->
    <div class="order-pay-info">
      <div class="order-pay-box">
        <p><strong class="title">결제정보</strong></p>
        <ul>
          <li>
            <span>상품 금액</span>
            <span>{{ order.product_id.price|intcomma}}원</span>
          </li>
          <li><span>배송비</span><span>0원</span></li>
          <li><span>할인비용</span><span>0원</span></li>
          <li>
            <span>총 결제 금액</span
            ><span class="color-orange"
              >{{ order.order_id.total_price|intcomma }}원</span
            >
          </li>
        </ul>
      </div>
      <div class="current-shipping-box">
        <p><strong class="title">배송 현황</strong></p>
        <div class="col">
          <p>택배배송</p>
          <p>온라인 물류센터</p>
        </div>
        <p class="col">
          {% if not order.status %}
          <span>
            {{ order.status | convert_status }} <i class="xi-info"></i
          ></span>
          {% else %}
          <span> {{ order.status | convert_status }} </span>
          {% endif %}
        </p>
      </div>
    </div>
    <!-- 주문 정보 -->
    <div class="order-info-wrapper">
      <p>
        <strong class="title">배송주문상품</strong>
        <a href="../../product/detail/{{order.product_id.id}}"
          ><span>상품보러가기</span></a
        >
      </p>
      <div class="order-info-content">
        <div class="thumbNail-wrapper">
          <a href="../../product/detail/{{order.product_id.id}}">
            <img
              src="../../media/{{ order.product_id.thumbnail }}"
              alt="product-thumNail"
            />
          </a>
        </div>
        <div class="order-info-detail">
          <span class="order-info-title">{{ order.product_id.name }}</span>
          <p>
            <span class="order-info-style">{{ order.product_id.style }}</span>
            <span class="order-info-size">{{ order.size }}</span>
          </p>
          <span class="order-info-amount">{{ order.quantity }}</span>
          <span class="order-info-price"
            >{{ order.product_id.price|intcomma }}원</span
          >
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endif %} {% endblock %}

member/templates/member/profile-password.html
{% extends "member/profile-base.html" %}

<!-- 템플릿 확장 -->
{% load static %}
<!-- 링크 -->
{% block link %}
<link rel="stylesheet" href="{% static 'member/css/profile.css' %}" />
{% endblock %}

<!-- 타이틀 -->
{% block title %}개인정보수정-나이키{% endblock %}

<!-- content -->
{% block profileContent %}
<form
  method="POST"
  action="{% url 'member:profile-password' %}"
  id="profile-password"
>
  <h1 class="profile-update-title">비밀번호 변경</h1>
  {% csrf_token %} {{ password_change_form }}
  <input type="submit" value="변경하기" />
</form>
{% load static %}
<script src="{% static 'member/js/member.js' %}"></script>
{% endblock %}

member/templates/member/profile-update.html
{% extends "member/profile-base.html" %}

<!-- 타이틀 -->
{% block title %}개인정보수정-나이키{% endblock %}

<!-- 템플릿 확장 -->
{% load static %}
<!-- 링크 -->
{% block link %}
<link rel="stylesheet" href="{% static 'member/css/profile.css' %}" />
{% endblock %}

<!-- content -->
{% block profileContent %}

<form
  method="POST"
  action="{% url 'member:profile-update' %}"
  id="profile-update"
>
  <h1 class="profile-update-title">회원정보 수정</h1>
  {% csrf_token %} {{ user_change_form }}
  <input type="submit" value="수정하기" />
</form>
{% load static %}
<script src="{% static 'member/js/member.js' %}"></script>
{% endblock %}

member/templates/member/service-complete.html
{% extends "product/error.html" %}

<!-- Title -->
{% block title %}
<title>나이키 - 취소 신청 완료</title>
{% endblock %}

<!-- Comtent -->
{% block content %}
<p class="error-title">취소 신청이 완료 되었습니다</p>
<div class="error-content">
  <p>담당자에게 연락을 취했습니다.</p>
  <p>
    빠른 시일 내에 처리하여 환불 조치하겠습니다.
  </p>
</div>
{% endblock %}

member/templates/member/service.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>NIke-Clone 고객센터</title>
    <link
      href="{% static 'product/img/favicon.ico' %}"
      rel="icon"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'product/css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/service.css' %}" />
    <!-- jquery cdn -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'member/js/service.js' %}"></script>
    {% block link %}
    <!-- css / js -->
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="logo-wrapper">
        <a href="/"><div class="logo"></div></a>
      </div>
      {% block title %}
      <h2>고객센터</h2>
      {% endblock %}
    </header>
    {% block content %}
    <section>
      <ul class="mainList-wrapper">
        <li class="ul-title">
          <h2>FAQ</h2>
          <span>자주 찾는 질문에서 궁금한 내용을 찾아보세요</span>
        </li>
        <li class="col">
          <ul class="list-ul">
            <li class="list-title">나의 정보 조회</li>
            <li>
              <a href="{% url 'member:order' %}"><span>주문 내역 조회</span></a>
            </li>
            <li>
              <a href="/member/id-find/"><span>아이디 / 비밀번호 찾기</span></a>
            </li>
          </ul>
        </li>
        <li class="col">
          <ul class="list-ul">
            <li class="list-title">배송 / 취소 안내</li>
            <li>
              <a href="/member/service-cancel/"><span>주문 취소 신청</span></a>
            </li>
            <li>
              <a href="/member/service-cancelList/"
                ><span>주문 취소 내역</span></a
              >
            </li>
          </ul>
        </li>
        <li class="col">
          <ul class="list-ul">
            <li class="list-title">서비스 안내</li>
            <li>
              <a href="/member/profile-rate"><span>회원 혜택</span></a>
            </li>
            <li>
              <a href="https://github.com/Minsoo-web/Today-I-Learn/issues"
                ><span>기타 문의</span></a
              >
            </li>
          </ul>
        </li>
      </ul>
    </section>
    {% endblock %}
  </body>
</html>